CREATE TABLE CLIENTES (
	ID BIGINT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(250),
	ENDERECO VARCHAR(500),
	IDADE INTEGER, 
	ATIVO INTEGER(1)
); 

INSERT INTO CLIENTES
(NOME, ENDERECO, IDADE, ATIVO)
VALUES
('JOÃO DA SILVA PEDRO', 'RUA A, TRAVESSA B, BAIRRO C - 37', 37, 1);